{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"codeListing","syntax":"text","code":["Parameter frame: CGRect Pass your UI frame parameters.","Parameter url: Pass the URL string and it will safely unwrap or print out error in console."]},{"style":"warning","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If the url provided in initializer is valid. PlayerView will automatically play the video on start."}]}],"type":"aside","name":"Warning"},{"type":"codeListing","syntax":"swift","code":["var playerView: PlayerView?","playerView = PlayerView(frame: view.bounds, url: \"www.something.com\")","view.addSubview(playerView)"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/basicavplayer\/playerview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/basicavplayer\/playerview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sensehack.BasicAVPlayer\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)NSCoding","doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)NSObject","doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)CALayerDelegate","doc:\/\/com.sensehack.BasicAVPlayer\/s7CVarArgP","doc:\/\/com.sensehack.BasicAVPlayer\/s28CustomDebugStringConvertibleP","doc:\/\/com.sensehack.BasicAVPlayer\/s23CustomStringConvertibleP","doc:\/\/com.sensehack.BasicAVPlayer\/SQ","doc:\/\/com.sensehack.BasicAVPlayer\/SH","doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UIAppearance","doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UIAppearanceContainer","doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UICoordinateSpace","doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UIDynamicItem","doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UIFocusEnvironment","doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UIFocusItem","doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UIFocusItemContainer","doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UILargeContentViewerItem","doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UITraitEnvironment","doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sensehack.BasicAVPlayer\/documentation\/BasicAVPlayer\/PlayerView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates an UIView which will display AVPlayer with default videoURL resource provided while initialization"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"title":"PlayerView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@BasicAVPlayer@objc(cs)PlayerView","modules":[{"name":"BasicAVPlayer"}],"navigatorTitle":[{"kind":"identifier","text":"PlayerView"}]},"hierarchy":{"paths":[["doc:\/\/com.sensehack.BasicAVPlayer\/documentation\/BasicAVPlayer"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sensehack.BasicAVPlayer\/documentation\/BasicAVPlayer\/PlayerView\/init(frame:url:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sensehack.BasicAVPlayer\/documentation\/BasicAVPlayer\/PlayerView\/printCurrentVideoPlayheadPosition(timeValue:timeScale:)","doc:\/\/com.sensehack.BasicAVPlayer\/documentation\/BasicAVPlayer\/PlayerView\/subscribeToCurrentVideoStatus()"]}],"references":{"doc://com.sensehack.BasicAVPlayer/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UICoordinateSpace"},"doc://com.sensehack.BasicAVPlayer/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UIDynamicItem"},"doc://com.sensehack.BasicAVPlayer/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UITraitEnvironment"},"doc://com.sensehack.BasicAVPlayer/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UIFocusItem"},"doc://com.sensehack.BasicAVPlayer/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UIAppearance"},"doc://com.sensehack.BasicAVPlayer/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UIAccessibilityIdentification"},"doc://com.sensehack.BasicAVPlayer/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/s7CVarArgP"},"doc://com.sensehack.BasicAVPlayer/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/objc(cs)UIView"},"doc://com.sensehack.BasicAVPlayer/documentation/BasicAVPlayer":{"role":"collection","title":"BasicAVPlayer","abstract":[],"identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/documentation\/BasicAVPlayer","kind":"symbol","type":"topic","url":"\/documentation\/basicavplayer"},"doc://com.sensehack.BasicAVPlayer/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)NSObject"},"doc://com.sensehack.BasicAVPlayer/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UIFocusEnvironment"},"doc://com.sensehack.BasicAVPlayer/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UIFocusItemContainer"},"doc://com.sensehack.BasicAVPlayer/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/s28CustomDebugStringConvertibleP"},"doc://com.sensehack.BasicAVPlayer/documentation/BasicAVPlayer/PlayerView/init(frame:url:)":{"role":"symbol","title":"init(frame:url:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/documentation\/BasicAVPlayer\/PlayerView\/init(frame:url:)","kind":"symbol","type":"topic","url":"\/documentation\/basicavplayer\/playerview\/init(frame:url:)"},"doc://com.sensehack.BasicAVPlayer/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.sensehack.BasicAVPlayer/documentation/BasicAVPlayer/PlayerView/printCurrentVideoPlayheadPosition(timeValue:timeScale:)":{"role":"symbol","title":"printCurrentVideoPlayheadPosition(timeValue:timeScale:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"printCurrentVideoPlayheadPosition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"timeValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timeScale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tracks video player progress every seconds passed in the function."}],"identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/documentation\/BasicAVPlayer\/PlayerView\/printCurrentVideoPlayheadPosition(timeValue:timeScale:)","kind":"symbol","type":"topic","url":"\/documentation\/basicavplayer\/playerview\/printcurrentvideoplayheadposition(timevalue:timescale:)"},"doc://com.sensehack.BasicAVPlayer/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UIResponderStandardEditActions"},"doc://com.sensehack.BasicAVPlayer/documentation/BasicAVPlayer/PlayerView/subscribeToCurrentVideoStatus()":{"role":"symbol","title":"subscribeToCurrentVideoStatus()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribeToCurrentVideoStatus"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Prints video player playback status whenever it is in "},{"type":"codeVoice","code":".playing"},{"type":"text","text":" or "},{"type":"codeVoice","code":".paused"},{"type":"text","text":" state of type "},{"type":"codeVoice","code":"AVPlayer.TimeControlStatus"}],"identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/documentation\/BasicAVPlayer\/PlayerView\/subscribeToCurrentVideoStatus()","kind":"symbol","type":"topic","url":"\/documentation\/basicavplayer\/playerview\/subscribetocurrentvideostatus()"},"doc://com.sensehack.BasicAVPlayer/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/SH"},"doc://com.sensehack.BasicAVPlayer/documentation/BasicAVPlayer/PlayerView":{"role":"symbol","title":"PlayerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"abstract":[{"type":"text","text":"Creates an UIView which will display AVPlayer with default videoURL resource provided while initialization"}],"identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/documentation\/BasicAVPlayer\/PlayerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/basicavplayer\/playerview"},"doc://com.sensehack.BasicAVPlayer/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UILargeContentViewerItem"},"doc://com.sensehack.BasicAVPlayer/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.sensehack.BasicAVPlayer/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.sensehack.BasicAVPlayer/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)NSCoding"},"doc://com.sensehack.BasicAVPlayer/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/s23CustomStringConvertibleP"},"doc://com.sensehack.BasicAVPlayer/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UIAppearanceContainer"},"doc://com.sensehack.BasicAVPlayer/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)UIUserActivityRestoring"},"doc://com.sensehack.BasicAVPlayer/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/SQ"},"doc://com.sensehack.BasicAVPlayer/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/objc(pl)CALayerDelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PlayerView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PlayerView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PlayerView"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.sensehack.BasicAVPlayer\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sensehack.BasicAVPlayer~1documentation~1BasicAVPlayer~1PlayerView\/title","value":"PlayerView"},{"op":"replace","path":"\/references\/doc:~1~1com.sensehack.BasicAVPlayer~1documentation~1BasicAVPlayer~1PlayerView\/fragments","value":[{"kind":"identifier","text":"PlayerView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}