{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/basicavplayer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/basicavplayer"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sensehack.BasicAVPlayer\/documentation\/BasicAVPlayer","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.sensehack.BasicAVPlayer\/documentation\/BasicAVPlayer\/PlayerView"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"BasicAVPlayer","title":"BasicAVPlayer","symbolKind":"module","role":"collection","modules":[{"name":"BasicAVPlayer"}]},"hierarchy":{"paths":[[]]},"references":{"doc://com.sensehack.BasicAVPlayer/documentation/BasicAVPlayer/BasicAVPlayerVersionString":{"role":"symbol","title":"BasicAVPlayerVersionString","fragments":[{"kind":"identifier","text":"BasicAVPlayerVersionString"}],"abstract":[{"type":"text","text":"Project version string for BasicAVPlayer."}],"identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/documentation\/BasicAVPlayer\/BasicAVPlayerVersionString","kind":"symbol","type":"topic","url":"\/documentation\/basicavplayer\/basicavplayerversionstring"},"doc://com.sensehack.BasicAVPlayer/documentation/BasicAVPlayer":{"role":"collection","title":"BasicAVPlayer","abstract":[],"identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/documentation\/BasicAVPlayer","kind":"symbol","type":"topic","url":"\/documentation\/basicavplayer"},"doc://com.sensehack.BasicAVPlayer/documentation/BasicAVPlayer/PlayerView":{"role":"symbol","title":"PlayerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"abstract":[{"type":"text","text":"Creates an UIView which will display AVPlayer with default videoURL resource provided while initialization"}],"identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/documentation\/BasicAVPlayer\/PlayerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/basicavplayer\/playerview"},"doc://com.sensehack.BasicAVPlayer/documentation/BasicAVPlayer/BasicAVPlayerVersionNumber":{"role":"symbol","title":"BasicAVPlayerVersionNumber","fragments":[{"kind":"identifier","text":"BasicAVPlayerVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for BasicAVPlayer."}],"identifier":"doc:\/\/com.sensehack.BasicAVPlayer\/documentation\/BasicAVPlayer\/BasicAVPlayerVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/basicavplayer\/basicavplayerversionnumber"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/com.sensehack.BasicAVPlayer\/documentation\/BasicAVPlayer\/PlayerView"]},{"title":"Variables","identifiers":["doc:\/\/com.sensehack.BasicAVPlayer\/documentation\/BasicAVPlayer\/BasicAVPlayerVersionNumber","doc:\/\/com.sensehack.BasicAVPlayer\/documentation\/BasicAVPlayer\/BasicAVPlayerVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.sensehack.BasicAVPlayer~1documentation~1BasicAVPlayer~1PlayerView\/title","value":"PlayerView"},{"op":"replace","path":"\/references\/doc:~1~1com.sensehack.BasicAVPlayer~1documentation~1BasicAVPlayer~1PlayerView\/fragments","value":[{"kind":"identifier","text":"PlayerView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}